language: perl

perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

install:
    - cpanm Mojolicious~"<=6.39" || { cat ~/.cpanm/build.log ; false ; }
    - cpanm --installdeps . || { cat ~/.cpanm/build.log ; false ; }
    - cpanm Test::CheckManifest || { cat ~/.cpanm/build.log ; false ; }

script:
    - perl Makefile.PL
    - RELEASE_TESTING=1 make test
